# Generated by Django 5.1.7 on 2025-10-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzedString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(unique=True)),
                ('sha256_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('is_palindrome', models.BooleanField(editable=False)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
