# Generated by Django 5.1.7 on 2025-10-22 08:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analyzedstring',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='analyzedstring',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
